In [2]:
import os

import numpy as np
import pandas as pd
pd.options.display.max_columns = None

## Load unprocessed data

In [2]:
nhanes_df = pd.read_csv("data/dictionary_nhanes.csv")
# nhanes_df[nhanes_df["variable_codename_use"].isin(["SEQN", "SEQN_new", "MCD180F"])]

In [3]:
demogr_df = pd.read_csv("data/demographics_clean.csv")
demogr_df.head()

,SEQN,SEQN_new,AIALANGA,DMAETHN,DMAETHNR,DMARACE,DMARACER,DMDBORN4,DMDCITZN,DMDEDUC,DMDEDUC2,DMDEDUC3,DMDFMSIZ,DMDHHSIZ,DMDHHSZA,DMDHHSZB,DMDHHSZE,DMDHRAGE,DMDHRBR4,DMDHREDU,DMDHRGND,DMDHRMAR,DMDHSEDU,DMDMARTL,DMDSCHOL,DMDYRSUS,DMPCNTYR,DMPCREGN,DMPFIPSR,DMPFSEQ,DMPMETRO,DMQADFC,DMQMILIZ,FIAINTRP,FIALANG,FIAPROXY,HAA1,HAA2,HAA2A,HAA3,HAA4,HAA5,HAA6A,HAA6B,HAA6C,HAA6D,HAD2,HAINTVR,HALANG,HAV10R,HAV11,HAV1S,HAV2S,HAV3S,HAV4S,HAV5,HAV6S,HAV7R,HAV8,HAV9,HAVERS,HAY10,HAY6,HAY7,HAY8,HAY9,HFA13,HFAGERR,HFC1,HFC10,HFC11,HFC7S,HFC8S,HFC9,HFE1,HFE10,HFE11,HFE12,HFE13,HFE14,HFE15,HFE16,HFE17,HFE18,HFE2,HFE3,HFE4,HFE5,HFE6,HFE7,HFE8A,HFE8B,HFE8C,HFE8D,HFE8E,HFE9,HFF10,HFF11,HFF12A,HFF12B,HFF13A,HFF13B,HFF13DA,HFF13DB,HFF13E,HFF14A,HFF14B,HFF14D,HFF15A,HFF15B,HFF16A,HFF16B,HFF16D,HFF16E,HFF17A,HFF17B,HFF18,HFF20R,HFF4,HFF5,HFF6A,HFF6B,HFF6C,HFF6D,HFF7,HFF8,HFF9,HFHEMPL,HFHMLSV,HFHSEQN,HFINTVR,HFRELR,HFVERS,HSAGEU,HSAITMOR,HSDOIMO,HXPSESSR,HXPTIDW,HXPTIMO,HYAITMO,INDFMIN2,INDFMPIR,INDHHIN2,MIAINTRP,MIALANG,MIAPROXY,MXPSESSR,MXPTIDW,MXPTIMO,RIAGENDR,RIDAGEMN,RIDAGEYR,RIDEXAGM,RIDEXAGY,RIDEXMON,RIDEXPRG,RIDPREG,RIDRETH1,RIDRETH2,RIDRETH3,RIDSTATR,SDDSRVYR,SDJ1REPN,SDMVPSU,SDMVSTRA,SDPPHASE,SDPPSU1,SDPPSU2,SDPSTRA1,SDPSTRA2,SIAINTRP,SIALANG,SIAPROXY,WTINT2YR,WTINT4YR,WTIREP01,WTIREP02,WTIREP03,WTIREP04,WTIREP05,WTIREP06,WTIREP07,WTIREP08,WTIREP09,WTIREP10,WTIREP11,WTIREP12,WTIREP13,WTIREP14,WTIREP15,WTIREP16,WTIREP17,WTIREP18,WTIREP19,WTIREP20,WTIREP21,WTIREP22,WTIREP23,WTIREP24,WTIREP25,WTIREP26,WTIREP27,WTIREP28,WTIREP29,WTIREP30,WTIREP31,WTIREP32,WTIREP33,WTIREP34,WTIREP35,WTIREP36,WTIREP37,WTIREP38,WTIREP39,WTIREP40,WTIREP41,WTIREP42,WTIREP43,WTIREP44,WTIREP45,WTIREP46,WTIREP47,WTIREP48,WTIREP49,WTIREP50,WTIREP51,WTIREP52,WTMEC2YR,WTMEC4YR,WTMREP01,WTMREP02,WTMREP03,WTMREP04,WTMREP05,WTMREP06,WTMREP07,WTMREP08,WTMREP09,WTMREP10,WTMREP11,WTMREP12,WTMREP13,WTMREP14,WTMREP15,WTMREP16,WTMREP17,WTMREP18,WTMREP19,WTMREP20,WTMREP21,WTMREP22,WTMREP23,WTMREP24,WTMREP25,WTMREP26,WTMREP27,WTMREP28,WTMREP29,WTMREP30,WTMREP31,WTMREP32,WTMREP33,WTMREP34,WTMREP35,WTMREP36,WTMREP37,WTMREP38,WTMREP39,WTMREP40,WTMREP41,WTMREP42,WTMREP43,WTMREP44,WTMREP45,WTMREP46,WTMREP47,WTMREP48,WTMREP49,WTMREP50,WTMREP51,WTMREP52
0,3,I-3,NaN,NaN,1.0,NaN,1.0,1.0,NaN,NaN,3.0,NaN,4.0,4,NaN,NaN,NaN,2.0,1.0,1.0,2.0,2.0,NaN,5.0,NaN,NaN,37.0,4.0,6.0,3872.0,1.0,NaN,NaN,NaN,1.0,NaN,1.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7057.0,1.0,NaN,NaN,1.0,24.0,24.0,0.0,2.0,NaN,208.0,3.0,2.0,1.0,1.0,1.0,NaN,NaN,2.0,2.0,33.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2.0,2.0,1.0,1.0,2.0,1.0,4.0,8.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,7.0,2.0,7.0,2.0,2.0,1.0,1.0,NaN,NaN,2.0,2.0,2.0,2641.0,7057.0,3.0,1.0,2.0,261.0,1.0,NaN,NaN,NaN,NaN,2.0,0.641,NaN,NaN,1.0,NaN,1.0,6.0,1.0,1,NaN,21,262.0,NaN,NaN,NaN,NaN,1,NaN,NaN,2,-1,NaN,1,44,1.0,1.0,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4,I-4,NaN,NaN,1.0,NaN,1.0,1.0,NaN,NaN,4.0,NaN,3.0,3,NaN,NaN,NaN,3.0,1.0,2.0,1.0,1.0,NaN,1.0,NaN,NaN,37.0,4.0,6.0,4115.0,1.0,NaN,NaN,NaN,1.0,NaN,2.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7054.0,1.0,NaN,NaN,1.0,48.0,72.0,0.0,2.0,NaN,17.0,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,2.0,32.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,NaN,2.0,2.0,1.0,2.0,NaN,2.0,6.0,5.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,20.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,NaN,7054.0,4.0,1.0,2.0,384.0,3.0,NaN,NaN,NaN,NaN,16.0,4.803,NaN,NaN,1.0,NaN,3.0,2.0,4.0,2,NaN,32,384.0,NaN,NaN,NaN,NaN,1,NaN,NaN,2,-1,NaN,1,43,1.0,2.0,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9,I-9,NaN,NaN,3.0,NaN,1.0,1.0,NaN,NaN,4.0,NaN,4.0,4,NaN,NaN,NaN,3.0,1.0,3.0,1.0,1.0,NaN,1.0,NaN,NaN,37.0,4.0,6.0,4064.0,1.0,NaN,NaN,NaN,1.0,NaN,2.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7056.0,1.0,NaN,NaN,6.0,52.0,52.0,6.0,2.0,NaN,988.0,2.0,2.0,1.0,1.0,1.0,NaN,NaN,1.0,2.0,52.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,1.0,2.0,1.0,2.0,NaN,NaN,NaN,7.0,20.0,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,20.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,2646.0,7056.0,3.0,1.0,2.0,583.0,3.0,NaN,NaN,NaN,NaN,16.0,3.747,NaN,NaN,1.0,NaN,1.0,5.0,3.0,2,NaN,48,583.0,NaN,NaN,NaN,NaN,3,NaN,NaN,2,-1,NaN,2,43,1.0,1.0,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10,I-10,NaN,NaN,3.0,NaN,1.0,1.0,NaN,NaN,5.0,NaN,2.0,2,NaN,NaN,NaN,2.0,1.0,3.0,1.0,1.0,NaN,6.0,NaN,NaN,17.0,1.0,25.0,5386.0,1.0,NaN,NaN,NaN,1.0,NaN,2.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7003.0,1.0,1.0,NaN,3.0,104.0,12.0,0.0,2.0,NaN,156.0,4.0,1.0,1.0,1.0,1.0,NaN,NaN,2.0,2.0,32.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,9.0,3.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,20.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,10.0,7003.0,4.0,1.0,2.0,428.0,8.0,NaN,NaN,NaN,NaN,8.0,5.406,NaN,NaN,1.0,NaN,2.0,6.0,8.0,1,NaN,35,429.0,NaN,NaN,NaN,NaN,3,NaN,NaN,2,-1,NaN,1,6,1.0,2.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,I-11,NaN,NaN,1.0,NaN,1.0,1.0,NaN,NaN,1.0,NaN,5.0,5,NaN,NaN,NaN,3.0,1.0,1.0,1.0,1.0,NaN,1.0,NaN,NaN,13.0,4.0,4.0,8142.0,1.0,NaN,NaN,NaN,1.0,NaN,2.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,7024.0,1.0,NaN,NaN,1.0,52.0,52.0,0.0,2.0,NaN,1300.0,1.0,NaN,1.0,1.0,1.0,NaN,NaN,1.0,2.0,48.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,2.0,2.0,1.0,2.0,NaN,2.0,6.0,25.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,17.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,11.0,7024.0,3.0,1.0,2.0,582.0,2.0,NaN,NaN,NaN,NaN,6.0,1.676,NaN,NaN,1.0,NaN,1.0,5.0,2.0,1,NaN,48,583.0,NaN,NaN,NaN,NaN,1,NaN,NaN,2,-1,NaN,2,40,1.0,2.0,NaN,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
qs_df = pd.read_csv("data/questionnaire_clean.csv")
qs_df.head()

,Unnamed: 0,SEQN,SEQN_new,SDDSRVYR,AGQ030,ALQ101,ALQ110,ALQ111,ALQ120Q,ALQ120U,ALQ130,ALQ141Q,ALQ141U,ALQ151,ALQ155,ALQ160,ALQ170,ALQ270,ALQ280,ALQ290,BPD035,BPD058,BPD110A,BPD110B,BPD110C,BPD120,BPD130,BPD140,BPQ010,BPQ020,BPQ030,BPQ040A,BPQ040B,BPQ040C,BPQ040D,BPQ040E,BPQ040F,BPQ043A,BPQ043B,BPQ043C,BPQ043D,BPQ050A,BPQ050B,BPQ050C,BPQ050D,BPQ050E,BPQ052,BPQ056,BPQ057,BPQ059,BPQ060,BPQ070,BPQ080,BPQ090A,BPQ090B,BPQ090C,BPQ090D,BPQ100A,BPQ100B,BPQ100C,BPQ100D,DID040,DID040G,DID040Q,DID250,DID270,DID310D,DID310S,DID320,DID330,DID341,DID350,DIQ010,DIQ050,DIQ060,DIQ060G,DIQ060Q,DIQ060U,DIQ070,DIQ080,DIQ090,DIQ100,DIQ110,DIQ120,DIQ130,DIQ140,DIQ150,DIQ160,DIQ170,DIQ172,DIQ175A,DIQ175B,DIQ175C,DIQ175D,DIQ175E,DIQ175F,DIQ175G,DIQ175H,DIQ175I,DIQ175J,DIQ175K,DIQ175L,DIQ175M,DIQ175N,DIQ175O,DIQ175P,DIQ175Q,DIQ175R,DIQ175S,DIQ175T,DIQ175U,DIQ175V,DIQ175W,DIQ175X,DIQ180,DIQ190A,DIQ190B,DIQ190C,DIQ200A,DIQ200B,DIQ200C,DIQ220,DIQ230,DIQ240,DIQ260,DIQ260U,DIQ275,DIQ280,DIQ290,DIQ300D,DIQ300S,DIQ350U,DIQ360,ECD010,ECD070A,ECD070B,ECQ020,ECQ030,ECQ040,ECQ060,ECQ080,ECQ090,ECQ100,ECQ110,ECQ130,ECQ140,ECQ150,FSQ121,HAB2,HAB3,HAB4,HAB5,HAB6S,HAB7,HAC1H,HAC1I,HAC1L,HAC1N,HAC2H,HAC3HR,HAC3IR,HAC3LR,HAC3NR,HAC3OR,HAC3OS,HAC5A1,HAC5A10,HAC5A11,HAC5A12,HAC5A2,HAC5A3,HAC5A4,HAC5A5,HAC5A6,HAC5A7,HAC5A8,HAC5A9,HAC5B1,HAC5B10,HAC5B11,HAC5B12,HAC5B2,HAC5B3,HAC5B4,HAC5B5,HAC5B6,HAC5B7,HAC5B8,HAC5B9,HAC7A,HAD11AS,HAD12S,HAD14,HAD3,HAD4,HAD7S,HAD8,HAE1,HAE10,HAE11A,HAE11B,HAE11C,HAE3,HAE4B,HAE4C,HAE4D,HAE4D1,HAE4D2,HAE4D3,HAE4D4,HAE4D5,HAE4D6,HAE5A,HAE5B,HAE5C,HAE5D1,HAE5D2,HAE5D3,HAE5D4,HAE5D5,HAE5D6,HAE6,HAE7,HAE8A,HAE8B,HAE8C,HAE8D,HAE9A,HAE9B,HAE9C,HAE9D,HAF1,HAF11,HAF13R,HAF14,HAF15,HAF16,HAF17,HAF18,HAF19,HAF2,HAF20,HAF21,HAF22,HAF23,HAF24,HAF25,HAF26,HAF27,HAF3,HAF4,HAF5,HAF6,HAF7A,HAF7B,HAF7C,HAF7D,HAF7E,HAF7F,HAF7G,HAF7H,HAF9,HAG1,HAG10A,HAG10B,HAG10C,HAG10D,HAG10E,HAG10F,HAG11,HAG12,HAG13,HAG14,HAG15,HAG16,HAG17A,HAG17AA,HAG17B,HAG17BB,HAG17C,HAG17CC,HAG17D,HAG17DD,HAG17E,HAG17EE,HAG17F,HAG17FF,HAG17G,HAG17H,HAG17I,HAG17J,HAG17K,HAG17L,HAG17M,HAG17N,HAG17O,HAG17P,HAG17Q,HAG17R,HAG17S,HAG17T,HAG17U,HAG17V,HAG17W,HAG17X,HAG17Y,HAG17Z,HAG18,HAG19A,HAG19AA,HAG19B,HAG19BB,HAG19C,HAG19CC,HAG19D,HAG19DD,HAG19E,HAG19EE,HAG19F,HAG19FF,HAG19G,HAG19H,HAG19I,HAG19J,HAG19K,HAG19L,HAG19M,HAG19N,HAG19O,HAG19P,HAG19Q,HAG19R,HAG19S,HAG19T,HAG19U,HAG19V,HAG19W,HAG19X,HAG19Y,HAG19Z,HAG2,HAG20,HAG21,HAG22,HAG23,HAG24,HAG25,HAG26,HAG27,HAG28,HAG29,HAG3,HAG30,HAG31,HAG32,HAG33,HAG34,HAG4A,HAG4B,HAG4C,HAG5A,HAG5B,HAG5C,HAG6A,HAG6B,HAG6C,HAG7,HAG8A,HAG8B,HAG8C,HAG8D,HAG8E,HAG8F,HAG9AR,HAG9BR,HAG9CR,HAG9DR,HAG9ER,HAG9FR,HAH1,HAH10,HAH11,HAH12,HAH13,HAH14,HAH15,HAH16,HAH17,HAH2,HAH3,HAH4,HAH5,HAH6,HAH7,HAH8,HAH9,HAJ0,HAJ10,HAJ11,HAJ14,HAJ15,HAJ2A,HAJ2B,HAJ2C,HAJ3S,HAJ4,HAJ5,HAJ6,HAJ8,HAK1,HAK10,HAK11,HAK12,HAK13,HAK14,HAK2,HAK3A,HAK3A1,HAK3B,HAK3B1R,HAK3C,HAK3C1R,HAK4,HAK5,HAK6,HAK7,HAK8,HAK9,HAL1,HAL10,HAL11A,HAL11B,HAL12,HAL13,HAL14A,HAL14B,HAL14C,HAL14D,HAL14E,HAL15A,HAL15B,HAL15C,HAL15D,HAL15E,HAL15F,HAL15G,HAL15H,HAL15I,HAL15J,HAL15K,HAL15L,HAL15M,HAL16A,HAL16B,HAL17,HAL18,HAL19A,HAL19B,HAL19C,HAL2,HAL20A,HAL20B,HAL20C,HAL3,HAL4,HAL5,HAL6,HAL7,HAL8,HAL9,HAM1,HAM10S,HAM11,HAM12,HAM13,HAM14,HAM15A,HAM15B,HAM15C,HAM15D,HAM15E,HAM15F,HAM15G,HAM15H,HAM15K,HAM15L,HAM15M,HAM15N,HAM15O,HAM15P,HAM15Q,HAM15R,HAM15S,HAM15T,HAM15U,HAM15V,HAM15W,HAM15X,HAM15Y,HAM15Z,HAM2,HAM3,HAM4,HAM5S,HAM6S,HAM7,HAM8S,HAM9S,HAN10A,HAN10B,HAN10C,HAN10D,HAN10E,HAN1AS,HAN1BS,HAN1C,HAN1D,HAN1ES,HAN1FS,HAN1GS,HAN1HS,HAN1IS,HAN2AS,HAN2BS,HAN2CS,HAN2DS,HAN2ES,HAN2FS,HAN2GS,HAN2HS,HAN2IS,HAN2JS,HAN3AS,HAN3BS,HAN3CS,HAN3DS,HAN3ES,HAN3FS,HAN4AS,HAN4BS,HAN4CS,HAN4DS,HAN4ES,HAN4FS,HAN4GS,HAN4HS,HAN4IS,HAN4JS,HAN4KS,HAN4LS,HAN5AS,HAN5BS,HAN5CS,HAN5DS,HAN5ES,HAN5FS,HAN5GS,HAN5HS,HAN5IS,HAN5JS,HAN5KS,HAN5LS,HAN6AS,HAN6BS,HAN6CS,HAN6DS,HAN6ES,HAN6FS,HAN6GS,HAN6HS,HAN6IS,HAN6JS,HAN7AS,HAN7BS,HAN7CS,HAN8,HAN8ACD,HAN8AS,HAN8BCD,HAN8BS,HAN8CCD,HAN8CS,HAN8DCD,HAN8DS,HAN8ECD,HAN8ES,HAN8FCD,HAN8FS,HAN9,HAP1,HAP10,HAP10A,HAP11,HAP12,HAP13,HAP14,HAP15,HAP16,HAP17A1,HAP17A2,HAP17A3,HAP17B,HAP18A,HAP18B,HAP18C,HAP18D,HAP18E,HAP19A,HAP19B,HAP19C,HAP1A,HAP2,HAP4,HAP5,HAP6,HAP7,HAP8,HAP9,HAQ1,HAQ2A,HAQ2B,HAQ2C,HAQ2D,HAQ2E,HAQ2F,HAQ2G,HAQ2I,HAQ2K,HAQ2L,HAQ3S,HAQ4,HAQ5,HAQ6,HAQ7,HAQ8,HAQ9,HAR1,HAR10,HAR11R,HAR12S,HAR13,HAR14,HAR15,HAR16,HAR17,HAR18AS,HAR18BS,HAR19A,HAR19B,HAR2,HAR20R,HAR21,HAR22,HAR23,HAR24,HAR25,HAR26,HAR27,HAR28,HAR3,HAR4S,HAR5,HAR6,HAR7S,HAR8,HAR9,HAT10,HAT10MET,HAT11S,HAT12,HAT12MET,HAT13S,HAT14,HAT14MET,HAT16MET,HAT18,HAT19CD,HAT19MET,HAT1MET,HAT1S,HAT2,HAT20S,HAT21CD,HAT21MET,HAT22S,HAT23CD,HAT23MET,HAT24S,HAT25CD,HAT25MET,HAT26S,HAT29,HAT2MET,HAT3S,HAT4MET,HAT6,HAT6MET,HAT7S,HAT8,HAT8MET,HAT9S,HAX11AG,HAX11AH,HAX11AI,HAX11AJ,HAX11AK,HAX11AL,HAX11AM,HAX11AN,HAX11AO,HAX11AP,HAX11AQ,HAX11AR,HAX11AS,HAX11AT,HAX11AU,HAX11AV,HAX12SG,HAX12SH,HAX12SI,HAX12SJ,HAX12SK,HAX12SL,HAX12SM,HAX12SN,HAX12SO,HAX12SP,HAX12SQ,HAX12SR,HAX12SS,HAX12ST,HAX12SU,HAX12SV,HAX13AG,HAX13AH,HAX13AI,HAX13AJ,HAX15SG,HAX15SH,HAX15SI,HAX15SJ,HAX16A1G,HAX16A1H,HAX16A1I,HAX16A1J,HAX16AG,HAX16AH,HAX16AI,HAX16AJ,HAX17SG,HAX17SH,HAX17SI,HAX17SJ,HAX18A,HAX18B,HAX18C,HAX18D,HAX18DB,HAX18E,HAX18EB,HAX18F,HAX18FB,HAX18G,HAX18GB,HAX19AS,HAX19BS,HAX19CS,HAX19DS,HAX19ES,HAX19FS,HAX19GS,HAX1A,HAX1B,HAX1C,HAX2A,HAX2B,HAX2C,HAX3CG,HAX3CH,HAX3CI,HAX3CJ,HAX3CK,HAX3CL,HAX3CM,HAX3CN,HAX3CO,HAX3CP,HAX3CQ,HAX3CR,HAX3CS,HAX3CT,HAX3CU,HAX3CV,HAX3CW,HAX3DG,HAX3DH,HAX3DI,HAX3DJ,HAX3DK,HAX3DL,HAX3DM,HAX3DN,HAX3DO,HAX3DP,HAX3DQ,HAX3DR,HAX3DS,HAX3DT,HAX3DU,HAX3DV,HAX3DW,HAX6SG,HAX6SH,HAX6SI,HAX6SJ,HAX6SK,HAX6SL,HAX6SM,HAX6SN,HAX6SO,HAX6SP,HAX6SQ,HAX6SR,HAX6SS,HAX6ST,HAX6SU,HAX6SV,HAX6SW,HAX8SG,HAX8SH,HAX8SI,HAX8SJ,HAX8SK,HAX8SL,HAX8SM,HAX8SN,HAX8SO,HAX8SP,HAX8SQ,HAX8SR,HAX8SS,HAX8ST,HAX8SU,HAX8SV,HAX8SW,HAX9DG,HAX9DH,HAX9DI,HAX9DJ,HAX9DK,HAX9DL,HAX9DM,HAX9DN,HAX9DO,HAX9DP,HAX9DQ,HAX9DR,HAX9DS,HAX9DT,HAX9DU,HAX9DV,HAX9EG,HAX9EH,HAX9EI,HAX9EJ,HAX9EK,HAX9EL,HAX9EM,HAX9EN,HAX9EO,HAX9EP,HAX9EQ,HAX9ER,HAX9ES,HAX9ET,HAX9EU,HAX9EV,HAX9FG,HAX9FH,HAX9FI,HAX9FJ,HAX9FK,HAX9FL,HAX9FM,HAX9FN,HAX9FO,HAX9FP,HAX9FQ,HAX9FR,HAX9FS,HAX9FT,HAX9FU,HAX9FV,HFB1,HFB10,HFB11,HFB11A,HFB11B,HFB11C,HFB11D,HFB11E,HFB12,HFB13,HFB14AB,HFB14AC,HFB14AD,HFB14AE,HFB14AF,HFB14AG,HFB14AI,HFB14BA,HFB14BB,HFB14BC,HFB14BD,HFB14BE,HFB14BF,HFB14BG,HFB14BH,HFB16A,HFB16B,HFB17,HFB2,HFB3,HFB4,HFB5,HFB6,HFB7,HFB8,HFB9,HFC6A1,HFC6B,HFC6B1,HFC6C,HFC6C1,HFC6D,HFC6D1,HFC6E,HFC6E1,HFF1,HFF2R,HFF3A,HFF3B,HFF3C,HFF3D,HFF3E,HFF3F,HSAQUEX,HSD010,HSQ470,HSQ480,HSQ490,HSQ493,HSQ496,HSQ500,HSQ510,HSQ520,HSQ571,HSQ580,HSQ590,MAPF12R,MAPF14,MAPF15,MAPF16,MAPF17,MAPF18S,MAPF22,MAPF32S,MAPF34A,MAPF34B,MAPF34CS,MAPF36,MAPF37,MAPF39S,MAPF42,MAPF43S,MAPF44,MAPF46,MAPF47S,MAPF48,MAPF50,MAPF51,MAPF53,MAPF54R,MAPF55,MAPF56,MAPF57,MCD093,MCD160M,MCD170M,MCD180A,MCD180B,MCD180C,MCD180D,MCD180E,MCD180F,MCD180G,MCD180K,MCD180L,MCD180M,MCD180N,MCD240A,MCD240B,MCD240C,MCD330,MCQ010,MCQ025,MCQ035,MCQ040,MCQ050,MCQ051,MCQ053,MCQ060,MCQ070,MCQ075,MCQ080,MCQ080E,MCQ082,MCQ083,MCQ084,MCQ086,MCQ090,MCQ092,MCQ100,MCQ110,MCQ114,MCQ117Q,MCQ117U,MCQ120B,MCQ120C,MCQ120D,MCQ140,MCQ149,MCQ150G,MCQ150Q,MCQ151,MCQ160A,MCQ160B,MCQ160C,MCQ160D,MCQ160E,MCQ160F,MCQ160G,MCQ160H,MCQ160J,MCQ160K,MCQ160L,MCQ160M,MCQ160N,MCQ160O,MCQ170H,MCQ170K,MCQ170L,MCQ170M,MCQ180H,MCQ195,MCQ200,MCQ203,MCQ206,MCQ210,MCQ220,MCQ230A,MCQ230B,MCQ230C,MCQ230D,MCQ240A,MCQ240AA,MCQ240B,MCQ240BB,MCQ240C,MCQ240CC,MCQ240D,MCQ240DD,MCQ240DK,MCQ240E,MCQ240F,MCQ240G,MCQ240H,MCQ240I,MCQ240J,MCQ240K,MCQ240L,MCQ240M,MCQ240N,MCQ240O,MCQ240P,MCQ240Q,MCQ240R,MCQ240S,MCQ240T,MCQ240U,MCQ240V,MCQ240W,MCQ240X,MCQ240Y,MCQ240Z,MCQ245A,MCQ245B,MCQ250B,MCQ250D,MCQ250E,MCQ250F,MCQ260AA,MCQ260AB,MCQ260AC,MCQ260AD,MCQ260AE,MCQ260AF,MCQ260AG,MCQ260AH,MCQ260AI,MCQ260BA,MCQ260BB,MCQ260BC,MCQ260BD,MCQ260BE,MCQ260BF,MCQ260BG,MCQ260BH,MCQ260BI,MCQ260CA,MCQ260CB,MCQ260CC,MCQ260CD,MCQ260CE,MCQ260CF,MCQ260CG,MCQ260CH,MCQ260CI,MCQ260DA,MCQ260DB,MCQ260DC,MCQ260DD,MCQ260DE,MCQ260DF,MCQ260DG,MCQ260DH,MCQ260DI,MCQ260EA,MCQ260EB,MCQ260EC,MCQ260ED,MCQ260EE,MCQ260EF,MCQ260EG,MCQ260EH,MCQ260EI,MCQ260FA,MCQ260FB,MCQ260FC,MCQ260FD,MCQ260FE,MCQ260FF,MCQ260FG,MCQ260FH,MCQ260FI,MCQ260GA,MCQ260GB,MCQ260GC,MCQ260GD,MCQ260GE,MCQ260GF,MCQ260GG,MCQ260GH,MCQ260GI,MCQ265,MCQ267E,MCQ268A,MCQ268B,MCQ268C,MCQ268D,MCQ270,MCQ280,MCQ290,MCQ300A,MCQ300B,MCQ300C,MCQ310,MCQ320,MCQ340,MCQ350,MCQ366A,MCQ366B,MCQ366C,MCQ366D,MCQ371A,MCQ371B,MCQ371C,MCQ371D,MCQ380,MCQ510A,MCQ510B,MCQ510C,MCQ510D,MCQ510E,MCQ510F,MCQ520,MCQ530,MCQ540,MCQ550,MCQ560,MCQ570,MYPC19,MYPC20,MYPC21,MYPC22,MYPC23S,MYPC27R,MYPC28,MYPC7S,OSQ230,PAAQUEX,PAD020,PAD120,PAD160,PAD200,PAD320,PAD440,PAD460,PAD480,PAD570,PAD615,PAD630,PAD645,PAD660,PAD675,PAD680,PAD733,PAQ050Q,PAQ050U,PAQ100,PAQ180,PAQ500,PAQ520,PAQ540,PAQ560,PAQ580,PAQ605,PAQ610,PAQ620,PAQ625,PAQ635,PAQ640,PAQ650,PAQ655,PAQ665,PAQ670,PAQ677,PAQ678,PAQ679,PAQ706,PAQ710,PAQ715,PAQ722,PAQ724A,PAQ724AA,PAQ724AB,PAQ724AC,PAQ724AD,PAQ724AE,PAQ724AF,PAQ724B,PAQ724C,PAQ724CM,PAQ724D,PAQ724E,PAQ724F,PAQ724G,PAQ724H,PAQ724I,PAQ724J,PAQ724K,PAQ724L,PAQ724M,PAQ724N,PAQ724O,PAQ724P,PAQ724Q,PAQ724R,PAQ724S,PAQ724T,PAQ724U,PAQ724V,PAQ724W,PAQ724X,PAQ724Y,PAQ724Z,PAQ731,PAQ740,PAQ742,PAQ744,PAQ746,PAQ748,PAQ750,PAQ755,PAQ759A,PAQ759B,PAQ759C,PAQ759D,PAQ759E,PAQ759F,PAQ759G,PAQ759H,PAQ759I,PAQ759J,PAQ759K,PAQ759L,PAQ759M,PAQ759N,PAQ759O,PAQ759P,PAQ759Q,PAQ759R,PAQ759S,PAQ759T,PAQ759U,PAQ759V,PAQ762,PAQ764,PAQ766,PAQ770,PAQ772A,PAQ772B,PAQ772C,RHD018,RHD043,RHD080,RHD120,RHD143,RHD152,RHD173,RHD180,RHD190,RHD230,RHD270,RHD280,RHD350,RHD442,RHD451,RHD470,RHQ010,RHQ020,RHQ030,RHQ031,RHQ051,RHQ060,RHQ070,RHQ074,RHQ076,RHQ078,RHQ090,RHQ100,RHQ110,RHQ131,RHQ160,RHQ162,RHQ163,RHQ166,RHQ169,RHQ171,RHQ172,RHQ197,RHQ200,RHQ205,RHQ210,RHQ240A,RHQ240B,RHQ240C,RHQ240D,RHQ240E,RHQ240F,RHQ250,RHQ260,RHQ291,RHQ300,RHQ305,RHQ310,RHQ320,RHQ330,RHQ332,RHQ340,RHQ360,RHQ370,RHQ380,RHQ390,RHQ395,RHQ420,RHQ430,RHQ460Q,RHQ460U,RHQ510,RHQ520,RHQ540,RHQ542A,RHQ542B,RHQ542C,RHQ542D,RHQ550,RHQ551A,RHQ551B,RHQ551C,RHQ551D,RHQ551E,RHQ551F,RHQ551G,RHQ554,RHQ556,RHQ558,RHQ560Q,RHQ560U,RHQ562,RHQ564,RHQ566,RHQ568Q,RHQ568U,RHQ570,RHQ572,RHQ574,RHQ576Q,RHQ576U,RHQ580,RHQ582,RHQ584,RHQ586Q,RHQ586U,RHQ596,RHQ598,RHQ600,RHQ602Q,RHQ602U,RHQ700,RHQ710A,RHQ710B,RHQ710C,RHQ710D,RHQ710E,RHQ710F,RHQ710G,RHQ720,RHQ730,RHQ740,RHQ750A,RHQ750B,RHQ750C,VNRHQ51,WHQ030E
0,1,3.0,I-3,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,0.0,0.0,12.0,55.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,2.0,NaN,NaN,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,3.0,2.0,1.0,2.0,2.0,NaN,1.0,NaN,NaN,2.0,NaN,2.0,2.0,NaN,NaN,NaN,1.0,185.0,3.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,72.0,180.0,1.0,NaN,NaN,2.0,3.0,4.0,NaN,NaN,10.0,9.0,2.0,1.0,0.0,9.0,13.0,2.0,2.0,1.0,4.0,2.0,NaN,9.0,9.0,0.0,4.0,9.0,4.0,9.0,4.0,9.0,0.0,0.0,9.0,4.0,4.0,0.0,13.0,3.0,4.0,0.0,1.0,0.0,0.0,0.0,17.0,6.0,2.0,0.0,0.0,0.0,3.0,9.0,0.0,4.0,4.0,9.0,0.0,9.0,4.0,1.0,0.0,30.0,0.0,4.0,2.0,0.0,1.0,NaN,13.0,9.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,2.0,2.0,1.0,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN,1.0,NaN,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,730.0,4.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,3.0,1.0,15050.0,6.0,3.5,5.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,10.0,NaN,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,4.0,NaN,4.0,0.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,2.0,2.0,2.0,2.0,NaN,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
qs_df = pd.read_csv("data/questionnaire_clean.csv")
qs_df.head()

,Unnamed: 0,SEQN,SEQN_new,SDDSRVYR,AGQ030,ALQ101,ALQ110,ALQ111,ALQ120Q,ALQ120U,...,RHQ710F,RHQ710G,RHQ720,RHQ730,RHQ740,RHQ750A,RHQ750B,RHQ750C,VNRHQ51,WHQ030E
0,1,3.0,I-3,-1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,4.0,I-4,-1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
2,3,9.0,I-9,-1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
3,4,10.0,I-10,-1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,11.0,I-11,-1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Process demographic data

In [4]:
demogr_df = demogr_df.loc[demogr_df["SEQN_new"].str.contains("C")]

demogr_cols = demogr_df.columns.values.tolist()
demogr_cols = [col for col in demogr_cols if "WTMREP" not in col]
demogr_cols = [col for col in demogr_cols if "WTIREP" not in col]
demogr_cols = demogr_cols[2:]

print(len(demogr_cols))
# print(demogr_cols)

175

In [5]:
demogr_df.describe()

,SEQN,AIALANGA,DMAETHN,DMAETHNR,DMARACE,DMARACER,DMDBORN4,DMDCITZN,DMDEDUC,DMDEDUC2,DMDEDUC3,DMDFMSIZ,DMDHHSIZ,DMDHHSZA,DMDHHSZB,DMDHHSZE,DMDHRAGE,DMDHRBR4,DMDHREDU,DMDHRGND,DMDHRMAR,DMDHSEDU,DMDMARTL,DMDSCHOL,DMDYRSUS,DMPCNTYR,DMPCREGN,DMPFIPSR,DMPFSEQ,DMPMETRO,DMQADFC,DMQMILIZ,FIAINTRP,FIALANG,FIAPROXY,HAA1,HAA2,HAA2A,HAA3,HAA4,HAA5,HAA6A,HAA6B,HAA6C,HAA6D,HAD2,HAINTVR,HALANG,HAV10R,HAV11,HAV1S,HAV2S,HAV3S,HAV4S,HAV5,HAV6S,HAV7R,HAV8,HAV9,HAVERS,HAY10,HAY6,HAY7,HAY8,HAY9,HFA13,HFAGERR,HFC1,HFC10,HFC11,HFC7S,HFC8S,HFC9,HFE1,HFE10,HFE11,HFE12,HFE13,HFE14,HFE15,HFE16,HFE17,HFE18,HFE2,HFE3,HFE4,HFE5,HFE6,HFE7,HFE8A,HFE8B,HFE8C,HFE8D,HFE8E,HFE9,HFF10,HFF11,HFF12A,HFF12B,HFF13A,HFF13B,HFF13DA,HFF13DB,HFF13E,HFF14A,HFF14B,HFF14D,HFF15A,HFF15B,HFF16A,HFF16B,HFF16D,HFF16E,HFF17A,HFF17B,HFF18,HFF20R,HFF4,HFF5,HFF6A,HFF6B,HFF6C,HFF6D,HFF7,HFF8,HFF9,HFHEMPL,HFHMLSV,HFHSEQN,HFINTVR,HFRELR,HFVERS,HSAGEU,HSAITMOR,HSDOIMO,HXPSESSR,HXPTIDW,HXPTIMO,HYAITMO,INDFMIN2,INDFMPIR,INDHHIN2,MIAINTRP,MIALANG,MIAPROXY,MXPSESSR,MXPTIDW,MXPTIMO,RIAGENDR,RIDAGEMN,RIDAGEYR,RIDEXAGM,RIDEXAGY,RIDEXMON,RIDEXPRG,RIDPREG,RIDRETH1,RIDRETH2,RIDRETH3,RIDSTATR,SDDSRVYR,SDJ1REPN,SDMVPSU,SDMVSTRA,SDPPHASE,SDPPSU1,SDPPSU2,SDPSTRA1,SDPSTRA2,SIAINTRP,SIALANG,SIAPROXY,WTINT2YR,WTINT4YR,WTIREP01,WTIREP02,WTIREP03,WTIREP04,WTIREP05,WTIREP06,WTIREP07,WTIREP08,WTIREP09,WTIREP10,WTIREP11,WTIREP12,WTIREP13,WTIREP14,WTIREP15,WTIREP16,WTIREP17,WTIREP18,WTIREP19,WTIREP20,WTIREP21,WTIREP22,WTIREP23,WTIREP24,WTIREP25,WTIREP26,WTIREP27,WTIREP28,WTIREP29,WTIREP30,WTIREP31,WTIREP32,WTIREP33,WTIREP34,WTIREP35,WTIREP36,WTIREP37,WTIREP38,WTIREP39,WTIREP40,WTIREP41,WTIREP42,WTIREP43,WTIREP44,WTIREP45,WTIREP46,WTIREP47,WTIREP48,WTIREP49,WTIREP50,WTIREP51,WTIREP52,WTMEC2YR,WTMEC4YR,WTMREP01,WTMREP02,WTMREP03,WTMREP04,WTMREP05,WTMREP06,WTMREP07,WTMREP08,WTMREP09,WTMREP10,WTMREP11,WTMREP12,WTMREP13,WTMREP14,WTMREP15,WTMREP16,WTMREP17,WTMREP18,WTMREP19,WTMREP20,WTMREP21,WTMREP22,WTMREP23,WTMREP24,WTMREP25,WTMREP26,WTMREP27,WTMREP28,WTMREP29,WTMREP30,WTMREP31,WTMREP32,WTMREP33,WTMREP34,WTMREP35,WTMREP36,WTMREP37,WTMREP38,WTMREP39,WTMREP40,WTMREP41,WTMREP42,WTMREP43,WTMREP44,WTMREP45,WTMREP46,WTMREP47,WTMREP48,WTMREP49,WTMREP50,WTMREP51,WTMREP52
count,101316.000000,48266.000000,2.0,0.0,2.0,0.0,101300.000000,101282.000000,25920.000000,55075.000000,29475.000000,70190.000000,101316.000000,39156.000000,39156.000000,39156.000000,101301.000000,89042.000000,97813.000000,101301.000000,97366.000000,51027.000000,61563.000000,17708.000000,18360.000000,0.0,0.0,0.0,0.0,0.0,2182.000000,61335.000000,78835.000000,78835.000000,78835.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,99530.000000,92120.000000,96797.000000,55761.000000,55759.000000,55761.000000,0.0,0.0,0.0,101316.000000,63085.000000,101316.000000,73589.000000,3418.000000,96766.000000,19540.000000,5030.000000,101316.000000,31126.000000,39156.000000,101316.000000,101316.000000,9965.000000,101316.000000,101316.000000,0.0,0.0,0.0,0.0,0.0,80309.000000,80309.000000,80298.000000,101316.000000,21004.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,101316.000000,21004.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000,9965.000000
mean,51134.397193,1.111486,1.0,NaN,1.0,NaN,1.214709,1.116388,1.715895,3.316695,6.982901,3.669568,3.829148,0.532230,0.971703,0.420497,2.773319,1.350756,1.946664,1.479383,1.845357,2.025065,2.813411,1.368986,7.627288,NaN,NaN,NaN,NaN,NaN,1.501833,1.892443,1.976635,1.095402,1.998376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.117181,2.272155,9.928149,1.980291,1.080274,1.993723,NaN,NaN,NaN,1.507551,339.297725,31.128292,299.207232,9.641311,1.523407,1.996520,2.105765,2.895831,2.086584,3.356676,1.955091,5.425984,26.602107,1.522958,72.415719,NaN,NaN,NaN,NaN,NaN,1.973552,1.131143,1.627973,29454.061986,13266.627452,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,29454.061986,13266.627452,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720,27311.272720
std,29836.192620,0.337236,0.0,NaN,0.0,NaN,1.688598,0.414797,0.921383,1.318536,7.418173,1.780746,1.735352,0.811177,1.160525,0.716472,0.792074,2.340601,0.829088,0.499577,5.413961,0.844526,2.896013,0.649906,15.756810,NaN,NaN,NaN,NaN,NaN,0.585431,0.336269,0.151062,0.293771,0.040262,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.995891,1.601358,13.663710,0.139000,0.271719,0.078978,NaN,NaN,NaN,0.499945,287.483202,24.943081,272.492021,5.180846,0.499454,0.415657,1.345159,1.251255,1.099042,1.652314,0.207105,2.850576,14.884411,0.528267,42.927284,NaN,NaN,NaN,NaN,NaN,0.160464,0.337559,0.483348,29661.428173,13396.503004,30587.591454,30489.221325,30085.574506,30205.369265,30518.336962,30573.191458,30446.050516,30500.491844,30475.287811,30731.748930,31039.001980,30608.196584,30409.771302,30932.180156,31596.196218,31139.159146,30602.176000,30302.796262,30552.793345,30140.384588,30650.663307,30065.838654,30397.102612,30534.263321,30090.174338,30527.581591,31261.870837,30882.633906,30348.531153,30853.127193,30189.436248,30937.418175,30779.346169,30267.425896,30452.970913,30869.261867,30144.088091,30603.330977,30520.942541,30156.908196,30846.438559,31089.475104,30665.634827,30598.849901,31043.599738,30849.966003,30722.917655,30187.295946,30384.883527,30437.387382,30905.475866,30506.796274,30991.754208,14308.042972,33003.855301,32986.663807,32558.939351,32679.746775,32968.688238,33072.169711,32919.806332,32973.799251,32975.669759,33206.571273,33491.853484,33121.336851,32882.912291,33412.689669,34147.774724,33667.955810,33109.874028,32794.160567,32998.501957,32603.334190,33058.327004,32538.448271,32881.661203,33035.426953,32564.267449,32946.674666,33828.523152,33380.464257,32767.057206,33371.825055,32664.033012,33459.967153,33160.812779,32738.799720,32948.244675,33304.524703,32622.353384,33068.763430,33011.982711,32644.565292,33389.126998,33607.474213,33143.689458,33084.213992,33537.778412,33378.894820,33171.541786,32668.098238,32869.738597,32918.158666,33351.986280,33005.618479
min,1.000000,1.000000,1.0,NaN,1.0,NaN,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,974.665252,620.682382,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,25329.750000,1.000000,1.0,NaN,1.0,NaN,1.000000,1.000000,1.000000,2.000000,3.000000,2.000000,2.000000,0.000000,0.000000,0.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,NaN,NaN,NaN,NaN,NaN,1.000000,2.000000,2.000000,1.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,0.940000,5.000000,2.000000,1.000000,2.000000,NaN,NaN,NaN,1.000000,98.000000,10.000000,88.000000,5.000000,1.000000,2.000000,2.000000,2.000000,1.000000,2.000000,2.000000,3.000000,14.000000,1.000000,35.000000,NaN,NaN,NaN,NaN,NaN,2.000000,1.000000,1.000000,10006.870787,3338.769986,5879.187109,5837.649190,6016.249243,5993.320061,5849.181892,5857.075347,5873.310510,5910.641512,5870.408793,5822.707477,5773.586400,5836.440125,5875.759856,5781.642997,5684.441438,5744.216380,5843.433152,5979.879556,5895.029949,5994.444710,5825.399910,6051.640707,5943.991913,5931.707591,6074.976466,5871.215112,5705.287139,5827.998676,5946.170099,5786.080851,5995.685889,5762.901980,5811.452207,5984.325610,5957.186896,5763.009259,6020.634328,5851.899858,5860.804742,5992.175156,5809.682823,5745.473358,5872.353429,5825.399910,5736.731076,5806.159712,5823.602951,5988.851147,5887.751374,5908.787800,5812.202275,5803.128885,9468.776357,3060.235897,4729.559147,4324.162974,5119.002129,4955.486956,4711.724965,4702.541032,4833.379495,4644.796047,4794.567358,4675.138977,4608.932059,4591.454498,4614.254545,4726.841855,4389.885567,4594.389947,4497.156542,4835.110944,4746.795023,5072.213279,4642.179680,5013.623548,4865.072535,4825.582607,4876.533216,4715.509493,4492.751375,4603.361800,4870.215337,4545.423394,4980.297186,4545.293669,4687.922239,4816.935428,4702.473259,4723.138291,5020.760972,4669.638049,4849.944116,4989.935926,4515.733310,4631.167724,4681.711407,4684.248476,4591.770418,4586.465842,4624.535527,4819.116725,4687.108326,4760.662744,4651.105962,4336.436398
50%,50658.500000,1.000000,1.0,NaN,1.0,NaN,1.000000,1.000000,1.000000,3.000000,6.000000,4.000000,4.000000,0.000000,1.000000,0.000000,3.000000,1.000000,2.000000,1.000000,1.000000,2.000000,2.000000,1.000000,5.000000,NaN,NaN,NaN,NaN,NaN,1.000000,2.000000,2.000000,1.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,1.790000,7.000000,2.000000,1.000000,2.000000,NaN,NaN,NaN,2.000000,233.000000,24.000000,196.000000,9.000000,2.000000,2.000000,2.000000,3.000000,2.000000,3.000000,2.000000,5.000000,27.000000,2.000000,72.000000,NaN,NaN,NaN,NaN,NaN,2.000000,1.000000,2.000000,19136.901590,7794.768043,13214.431042,13264.684129,13355.248661,13386.424306,13403.163781,13312.502790,13223.169624,13443.460722,13266.772736,13134.514381,12785.651202,13398.703030,13332.319739,12819.819280,12382.176303,12619.469364,13479.133185,13359.618127,13214.160903,13390.612954,13049.413132,13392.060682,13364.011058,13207.881895,13383.807245,13303.533974,12461.832752,12947.757420,13380.764177,13060.484505,13405.665002,12739.698428,13186.135551,13437.449281,13359.900709,12934.489787,13409.165804,13206.704499,13210.661831,13416.750063,13129.673220,12649.597700,13329.955762,13144.352036,12602.772205,13029.465601,13136.748919,13383.851347,13241.702132,13319.694049,12998.691847,13483.749560,18914.925113,7046.365671,11453.279750,11612.410432,11725.298541,11672.572458,11616.669453,11573.997530,11457.284525,11715.144479,11479.779954,11435.305229,11162.101953,11583.050757,11683.586778,11200.745465,10867.939103,11033.301076,11693.349568,11543.842218,11517.169398,11692.451057,11505.733471,11687.625942,11506.453981,11446.258160,11693.121087,11570.473994,10976.050144,11281.298551,11634.298305,11305.571898,11710.529141,11101.492762,11463.260548,11595.820560,11710.820565,11250.530121,11630.618780,11571.963904,11464.366302,11643.134654,11327.293699,11061.612794,11508.588577,11472.402293,11042.319776,11316.597792,11517.295410,11751.861505,11634.992412,11684.109548,11390.033294,11743.104332
75%,77627.250000,1.000000,1.0,NaN,1.0,NaN,1.000000,1.000000,3.000000,4.000000,10.000000,5.000000,5.000000,1.000000,2.000000,1.000000,3.000000,2.000000,2.000000,2.000000,2.000000,3.000000,5.000000,2.000000,7.000000,NaN,NaN,NaN,NaN,NaN,2.000000,2.000000,2.000000,1.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.000000,3.570000,11.000000,2.000000,1.000000,2.000000,NaN,NaN,NaN,2.000000,560.000000,52.000000,483.000000,14.000000,2.000000,2.000000,2.000000,4.000000,3.000000,4.000000,2.000000,8.000000,39.000000,2.000000,109.000000,NaN,NaN,NaN,NaN,NaN,2.000000,1.000000,2.000000,36551.605358,18642.350091,39409.549115,40105.482452,39479.742247,39220.092166,39301.843573,39535.635663,39207.205422,39463.329763,39419.472584,39554.089386,39613.280343,39595.687548,40071.450914,39499.930507,39913.774483,39831.791049,39524.607218,39163.069536,39425.545399,39436.699342,39540.515573,39425.219821,39302.356472,39260.403314,39425.219821,39373.640565,39984.475490,39441.163538,39241.051307,39512.404047,39286.587444,39855.006802,39413.201330,39531.414758,39545.018000,39264.515565,39425.219821,39438.780193,39302.009822,39162.560594,39496.159718,39648.466058,39365.839763,39524.148907,40103.356146,39786.725033,39839.701043,39496.012125,39948.902129,39118.457922,39386.954612,40036.705287,37058.064768,18859.065973,40718.311919,41152.374901,40695.174321,40572.455353,40809.689590,40720.992919,40613.591841,40768.442717,40678.674773,40905.617341,40737.579918,40709.915247,41110.467803,40495.613837,40319.034814,40754.482680,41009.805760,40747.933190,40663.088456,40685.791485,40832.530102,40690.338154,40418.060430,40430.951177,40713.021433,40712.897381,40709.875287,40628.135855,40383.238923,40655.569876,40616.280303,40960.378757,40744.059944,40718.575165,40767.729145,40527.986942,40690.318158,40661.504649,40467.925478,40585.430351,40610.102744,40633.090878,40583.852449,40643.520669,40973.931970,40549.184034,40703.617156,40769.307708,41013.431220,40481.542742,40552.016945,40964.980755

In [6]:
# for _, row in nhanes_df[(nhanes_df["variable_codename_use"].isin(demogr_cols)) & (nhanes_df["in_dataset"] == "Demographics") & (nhanes_df["file_category"] == "Demographics")].iterrows():
#     print(row["variable_codename_use"])
#     print(row["variable_description_use"])
#     print()

In [7]:
demogr_features_df = demogr_df.loc[:, ["SEQN", "SEQN_new", "DMDCITZN", "DMDEDUC2", "DMDFMSIZ", "DMDMARTL", "INDFMPIR", "RIAGENDR", "RIDAGEYR"]]
print(demogr_features_df.shape)
demogr_features_df.head()

(101316, 9)

,SEQN,SEQN_new,DMDCITZN,DMDEDUC2,DMDFMSIZ,DMDMARTL,INDFMPIR,RIAGENDR,RIDAGEYR
33994,1,C-1,1.0,NaN,NaN,NaN,0.86,2,2
33995,2,C-2,1.0,5.0,NaN,NaN,5.00,1,77
33996,3,C-3,2.0,NaN,NaN,NaN,1.47,2,10
33997,4,C-4,1.0,NaN,NaN,NaN,0.57,1,1
33998,5,C-5,1.0,5.0,NaN,1.0,5.00,1,49

## Process questionnaire data (stroke data)

In [10]:
stroke_df = qs_df.loc[:, ["SEQN", "SEQN_new", "MCD180F"]]
# stroke_df = stroke_df.dropna()
stroke_df["SEQN"] = stroke_df["SEQN"].astype(int)
# stroke_df["MCD180F"] = stroke_df["MCD180F"].astype(int)

print(stroke_df.shape)
stroke_df.head()

(134515, 3)

   SEQN SEQN_new  MCD180F
0     3      I-3      NaN
1     4      I-4      NaN
2     9      I-9      NaN
3    10     I-10      NaN
4    11     I-11      NaN

## Make feature_df

In [44]:
# feature_df = pd.concat([demogr_features_df, stroke_df], keys=["SEQN", "SEQN_new"])
feature_df = pd.merge(demogr_features_df, stroke_df, on=["SEQN", "SEQN_new"])
print(feature_df.shape)
feature_df.head()

(101316, 10)

,SEQN,SEQN_new,DMDCITZN,DMDEDUC2,DMDFMSIZ,DMDMARTL,INDFMPIR,RIAGENDR,RIDAGEYR,MCD180F
0,1,C-1,1.0,NaN,NaN,NaN,0.86,2,2,NaN
1,2,C-2,1.0,5.0,NaN,NaN,5.00,1,77,NaN
2,3,C-3,2.0,NaN,NaN,NaN,1.47,2,10,NaN
3,4,C-4,1.0,NaN,NaN,NaN,0.57,1,1,NaN
4,5,C-5,1.0,5.0,NaN,1.0,5.00,1,49,NaN

In [16]:
feature_df.describe()

,SEQN,DMDCITZN,DMDEDUC2,DMDFMSIZ,DMDMARTL,INDFMPIR,RIAGENDR,RIDAGEYR,MCD180F
count,101316.000000,101282.000000,55075.000000,70190.000000,61563.000000,92120.000000,101316.000000,101316.000000,1946.000000
mean,51134.397193,1.116388,3.316695,3.669568,2.813411,2.272155,1.507551,31.128292,1908.183453
std,29836.192620,0.414797,1.318536,1.780746,2.896013,1.601358,0.499945,24.943081,13470.225104
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,16.000000
25%,25329.750000,1.000000,2.000000,2.000000,1.000000,0.940000,1.000000,10.000000,50.000000
50%,50658.500000,1.000000,3.000000,4.000000,2.000000,1.790000,2.000000,24.000000,62.000000
75%,77627.250000,1.000000,4.000000,5.000000,5.000000,3.570000,2.000000,52.000000,73.000000
max,102956.000000,9.000000,9.000000,7.000000,99.000000,5.000000,2.000000,85.000000,99999.000000

In [45]:
feature_df = feature_df.drop(feature_df[feature_df["MCD180F"] == 99999].index)
print(feature_df.shape)
feature_df.head()

(101280, 10)

,SEQN,SEQN_new,DMDCITZN,DMDEDUC2,DMDFMSIZ,DMDMARTL,INDFMPIR,RIAGENDR,RIDAGEYR,MCD180F
0,1,C-1,1.0,NaN,NaN,NaN,0.86,2,2,NaN
1,2,C-2,1.0,5.0,NaN,NaN,5.00,1,77,NaN
2,3,C-3,2.0,NaN,NaN,NaN,1.47,2,10,NaN
3,4,C-4,1.0,NaN,NaN,NaN,0.57,1,1,NaN
4,5,C-5,1.0,5.0,NaN,1.0,5.00,1,49,NaN

In [46]:
feature_df = feature_df.dropna(subset=["SEQN", "SEQN_new", "DMDCITZN", "DMDEDUC2", "DMDFMSIZ", "DMDMARTL", "INDFMPIR", "RIAGENDR", "RIDAGEYR"])
print(feature_df.shape)
feature_df.head()

(35897, 10)

,SEQN,SEQN_new,DMDCITZN,DMDEDUC2,DMDFMSIZ,DMDMARTL,INDFMPIR,RIAGENDR,RIDAGEYR,MCD180F
31129,31130,C-31130,1.0,4.0,1.0,2.0,1.99,2,85,NaN
31130,31131,C-31131,1.0,4.0,4.0,1.0,4.65,2,44,NaN
31131,31132,C-31132,1.0,5.0,2.0,1.0,5.00,1,70,NaN
31135,31136,C-31136,1.0,4.0,1.0,5.0,3.57,2,41,NaN
31143,31144,C-31144,1.0,3.0,6.0,5.0,0.46,1,21,NaN

In [47]:
feature_df = feature_df[(feature_df["SEQN_new"].str.contains("C")) & (feature_df["RIDAGEYR"] >= 55)]
feature_df["stroke"] = feature_df["MCD180F"].notna().astype(int)
print(feature_df.shape)
feature_df.head()

(14544, 11)

,SEQN,SEQN_new,DMDCITZN,DMDEDUC2,DMDFMSIZ,DMDMARTL,INDFMPIR,RIAGENDR,RIDAGEYR,MCD180F,stroke
31129,31130,C-31130,1.0,4.0,1.0,2.0,1.99,2,85,NaN,0
31131,31132,C-31132,1.0,5.0,2.0,1.0,5.00,1,70,NaN,0
31148,31149,C-31149,1.0,2.0,1.0,2.0,0.05,2,85,NaN,0
31149,31150,C-31150,1.0,3.0,1.0,3.0,1.22,1,79,NaN,0
31153,31154,C-31154,1.0,3.0,2.0,1.0,1.56,1,62,NaN,0

In [25]:
feature_df.describe()

,SEQN,DMDCITZN,DMDEDUC2,DMDFMSIZ,DMDMARTL,INDFMPIR,RIAGENDR,RIDAGEYR,MCD180F,stroke
count,14544.000000,14544.000000,14544.000000,14544.000000,14544.000000,14544.000000,14544.000000,14544.000000,987.000000,14544.000000
mean,68211.873212,1.082577,3.236180,2.328727,1.974354,2.543265,1.502682,67.975179,62.928065,0.067863
std,20840.372043,0.315305,1.349162,1.413371,2.147863,1.582049,0.500010,8.312412,13.239328,0.251519
min,31130.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,55.000000,16.000000,0.000000
25%,50057.250000,1.000000,2.000000,1.000000,1.000000,1.180000,1.000000,61.000000,55.000000,0.000000
50%,67617.000000,1.000000,3.000000,2.000000,1.000000,2.130000,2.000000,67.000000,64.000000,0.000000
75%,86667.500000,1.000000,4.000000,3.000000,3.000000,4.040000,2.000000,75.000000,73.000000,0.000000
max,102952.000000,9.000000,9.000000,7.000000,99.000000,5.000000,2.000000,85.000000,85.000000,1.000000

In [48]:
feature_df = feature_df.drop(["SEQN", "MCD180F"], axis=1)
print(feature_df.shape)
feature_df.head()

(14544, 9)

,SEQN_new,DMDCITZN,DMDEDUC2,DMDFMSIZ,DMDMARTL,INDFMPIR,RIAGENDR,RIDAGEYR,stroke
31129,C-31130,1.0,4.0,1.0,2.0,1.99,2,85,0
31131,C-31132,1.0,5.0,2.0,1.0,5.00,1,70,0
31148,C-31149,1.0,2.0,1.0,2.0,0.05,2,85,0
31149,C-31150,1.0,3.0,1.0,3.0,1.22,1,79,0
31153,C-31154,1.0,3.0,2.0,1.0,1.56,1,62,0

In [49]:
feature_df = feature_df.rename(columns={
    "DMDCITZN": "US_citizenship",
    "DMDEDUC2": "education_level",
    "DMDFMSIZ": "num_familiy",
    "DMDMARTL": "marital_status",
    "INDFMPIR": "PIR",
    "RIAGENDR": "gender",
    "RIDAGEYR": "age"
})
feature_df.head()

,SEQN_new,US_citizenship,education_level,num_familiy,marital_status,PIR,gender,age,stroke
31129,C-31130,1.0,4.0,1.0,2.0,1.99,2,85,0
31131,C-31132,1.0,5.0,2.0,1.0,5.00,1,70,0
31148,C-31149,1.0,2.0,1.0,2.0,0.05,2,85,0
31149,C-31150,1.0,3.0,1.0,3.0,1.22,1,79,0
31153,C-31154,1.0,3.0,2.0,1.0,1.56,1,62,0

In [51]:
# feature_df = feature_df.drop(feature_df[feature_df["US_citizenship"] == 9].index)
# feature_df = feature_df.drop(feature_df[feature_df["US_citizenship"] == 7].index)

feature_df["US_citizenship"] = feature_df["US_citizenship"].apply(lambda x: np.nan if x == 9 or x == 7 else x)
feature_df = feature_df.replace({"US_citizenship": {2.0: 0.0}})
# feature_df["US_citizenship"] = feature_df["US_citizenship"].astype(int)
print(feature_df.shape)
feature_df.head()

(14544, 9)

,SEQN_new,US_citizenship,education_level,num_familiy,marital_status,PIR,gender,age,stroke
31129,C-31130,1.0,4.0,1.0,2.0,1.99,2,85,0
31131,C-31132,1.0,5.0,2.0,1.0,5.00,1,70,0
31148,C-31149,1.0,2.0,1.0,2.0,0.05,2,85,0
31149,C-31150,1.0,3.0,1.0,3.0,1.22,1,79,0
31153,C-31154,1.0,3.0,2.0,1.0,1.56,1,62,0

In [58]:
feature_df[feature_df["US_citizenship"].isnull()]

,SEQN_new,US_citizenship,education_level,num_familiy,marital_status,PIR,gender,age,stroke
35295,C-35296,NaN,7.0,1.0,77.0,0.92,2,84,0
40761,C-40762,NaN,7.0,2.0,77.0,2.22,1,58,0
76170,C-77811,NaN,5.0,3.0,1.0,3.03,1,55,0
78688,C-80329,NaN,1.0,7.0,4.0,1.64,2,69,0
80144,C-81785,NaN,1.0,3.0,2.0,0.51,2,70,0
93236,C-94877,NaN,1.0,6.0,1.0,0.96,1,71,0
98622,C-100263,NaN,1.0,2.0,2.0,2.19,2,80,0
99536,C-101177,NaN,1.0,6.0,6.0,0.56,1,64,0

In [ ]:
# Value	Label	Unweighted
# Frequency	%
# 1	Less Than 9th Grade
# 366	10.3%
# 2	9-11th Grade (Includes 12th grade with no diploma)
# 563	15.9%
# 3	High School Grad/GED or Equivalent
# 826	23.3%
# 4	Some College or AA degree
# 1010	28.5%
# 5	College Graduate or above

In [59]:
# feature_df = feature_df.drop(feature_df[feature_df["education_level"] == 9].index)
# feature_df = feature_df.drop(feature_df[feature_df["education_level"] == 7].index)
# feature_df["education_level"] = feature_df["education_level"].astype(int)
feature_df["education_level"] = feature_df["education_level"].apply(lambda x: np.nan if x == 9 or x == 7 else x)
print(feature_df.shape)
feature_df.head()

(14544, 9)

,SEQN_new,US_citizenship,education_level,num_familiy,marital_status,PIR,gender,age,stroke
31129,C-31130,1.0,4.0,1.0,2.0,1.99,2,85,0
31131,C-31132,1.0,5.0,2.0,1.0,5.00,1,70,0
31148,C-31149,1.0,2.0,1.0,2.0,0.05,2,85,0
31149,C-31150,1.0,3.0,1.0,3.0,1.22,1,79,0
31153,C-31154,1.0,3.0,2.0,1.0,1.56,1,62,0

In [60]:
feature_df[feature_df["education_level"].isnull()]

,SEQN_new,US_citizenship,education_level,num_familiy,marital_status,PIR,gender,age,stroke
35295,C-35296,NaN,NaN,1.0,77.0,0.92,2,84,0
40761,C-40762,NaN,NaN,2.0,77.0,2.22,1,58,0
46589,C-46590,1.0,NaN,2.0,2.0,3.43,2,74,0
51236,C-51237,1.0,NaN,2.0,1.0,2.48,2,80,0
52270,C-52271,1.0,NaN,1.0,2.0,1.29,2,80,0
52661,C-52662,1.0,NaN,2.0,5.0,0.92,2,66,0
54235,C-54236,1.0,NaN,1.0,5.0,2.77,2,60,0
55066,C-55067,0.0,NaN,5.0,5.0,0.39,2,61,0
56518,C-56519,1.0,NaN,2.0,1.0,2.47,2,79,0
59931,C-59932,1.0,NaN,3.0,2.0,3.55,2,80,0
69694,C-69695,1.0,NaN,1.0,3.0,1.54,1,80,0
75550,C-77191,0.0,NaN,1.0,2.0,0.72,2,80,0
78246,C-79887,0.0,NaN,1.0,2.0,0.77,1,69,0
83633,C-85274,1.0,NaN,2.0,2.0,0.55,2,72,0
84357,C-85998,1.0,NaN,5.0,2.0,1.41,1,80,0
90536,C-92177,1.0,NaN,2.0,1.0,0.75,1,80,1
96134,C-97775,0.0,NaN,1.0,4.0,1.53,1,67,0
101200,C-102841,0.0,NaN,1.0,5.0,2.31,1,78,0

In [61]:
feature_df["num_familiy"] = feature_df["num_familiy"].astype(int)
print(feature_df.shape)
feature_df.head()

(14544, 9)

,SEQN_new,US_citizenship,education_level,num_familiy,marital_status,PIR,gender,age,stroke
31129,C-31130,1.0,4.0,1,2.0,1.99,2,85,0
31131,C-31132,1.0,5.0,2,1.0,5.00,1,70,0
31148,C-31149,1.0,2.0,1,2.0,0.05,2,85,0
31149,C-31150,1.0,3.0,1,3.0,1.22,1,79,0
31153,C-31154,1.0,3.0,2,1.0,1.56,1,62,0

In [62]:
# feature_df = feature_df.drop(feature_df[feature_df["marital_status"] == 99].index)
# feature_df = feature_df.drop(feature_df[feature_df["marital_status"] == 77].index)
# feature_df["marital_status"] = feature_df["marital_status"].astype(int)
feature_df["marital_status"] = feature_df["marital_status"].apply(lambda x: np.nan if x == 99 or x == 77 else x)
print(feature_df.shape)
feature_df.head()

(14544, 9)

,SEQN_new,US_citizenship,education_level,num_familiy,marital_status,PIR,gender,age,stroke
31129,C-31130,1.0,4.0,1,2.0,1.99,2,85,0
31131,C-31132,1.0,5.0,2,1.0,5.00,1,70,0
31148,C-31149,1.0,2.0,1,2.0,0.05,2,85,0
31149,C-31150,1.0,3.0,1,3.0,1.22,1,79,0
31153,C-31154,1.0,3.0,2,1.0,1.56,1,62,0

In [63]:
feature_df[feature_df["marital_status"].isnull()]

,SEQN_new,US_citizenship,education_level,num_familiy,marital_status,PIR,gender,age,stroke
35295,C-35296,NaN,NaN,1,NaN,0.92,2,84,0
37406,C-37407,1.0,5.0,1,NaN,5.00,1,55,0
40761,C-40762,NaN,NaN,2,NaN,2.22,1,58,0
56338,C-56339,1.0,4.0,2,NaN,2.75,1,55,0
67240,C-67241,1.0,3.0,3,NaN,0.81,1,80,0
77462,C-79103,1.0,3.0,1,NaN,1.49,2,80,0

In [64]:
feature_df = feature_df.replace({"gender": {1: 0, 2: 1}})
print(feature_df.shape)
feature_df.head()

(14544, 9)

,SEQN_new,US_citizenship,education_level,num_familiy,marital_status,PIR,gender,age,stroke
31129,C-31130,1.0,4.0,1,2.0,1.99,1,85,0
31131,C-31132,1.0,5.0,2,1.0,5.00,0,70,0
31148,C-31149,1.0,2.0,1,2.0,0.05,1,85,0
31149,C-31150,1.0,3.0,1,3.0,1.22,0,79,0
31153,C-31154,1.0,3.0,2,1.0,1.56,0,62,0

In [65]:
feature_df.to_csv("data/NHANES-C_processed.csv", index=False)

In [66]:
feature_df[feature_df["stroke"] == 1].shape

(987, 9)

In [67]:
feature_df[feature_df["stroke"] == 0].shape

(13557, 9)

## One-hot encoding for marital_status

In [3]:
df = pd.read_csv("data/NHANES-C_processed.csv")
print(df.shape)
df.head()

(14544, 9)

,SEQN_new,US_citizenship,education_level,num_familiy,marital_status,PIR,gender,age,stroke
0,C-31130,1.0,4.0,1,2.0,1.99,1,85,0
1,C-31132,1.0,5.0,2,1.0,5.00,0,70,0
2,C-31149,1.0,2.0,1,2.0,0.05,1,85,0
3,C-31150,1.0,3.0,1,3.0,1.22,0,79,0
4,C-31154,1.0,3.0,2,1.0,1.56,0,62,0

In [4]:
df = df.drop(df[df["marital_status"].isnull()].index)
print(df.shape)
df.head()

(14538, 9)

,SEQN_new,US_citizenship,education_level,num_familiy,marital_status,PIR,gender,age,stroke
0,C-31130,1.0,4.0,1,2.0,1.99,1,85,0
1,C-31132,1.0,5.0,2,1.0,5.00,0,70,0
2,C-31149,1.0,2.0,1,2.0,0.05,1,85,0
3,C-31150,1.0,3.0,1,3.0,1.22,0,79,0
4,C-31154,1.0,3.0,2,1.0,1.56,0,62,0

In [7]:
df["marital_status"] = df["marital_status"].astype(int)
pd.get_dummies(df["marital_status"], prefix="marital_status")

,marital_status_1,marital_status_2,marital_status_3,marital_status_4,marital_status_5,marital_status_6
0,False,True,False,False,False,False
1,True,False,False,False,False,False
2,False,True,False,False,False,False
3,False,False,True,False,False,False
4,True,False,False,False,False,False
...,...,...,...,...,...,...
14539,True,False,False,False,False,False
14540,True,False,False,False,False,False
14541,False,False,True,False,False,False
14542,True,False,False,False,False,False
14543,True,False,False,False,False,False

In [7]:
df["marital_status"].isnull().sum()

np.int64(6)